; Expose a UNIX socket so `supervisorctl` can control supervisord.
; The base image's supervisorctl config points at /var/run/supervisor.sock
; but nothing in the base image creates it, so we do it here.
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
